/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCaregiverRouteImport } from './routes/_authenticated/caregiver'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayFamilyRouteImport } from './routes/_authenticated/play.family'
import { Route as AuthenticatedPlayPairsRouteImport } from './routes/_authenticated/play.pairs'
import { Route as AuthenticatedPlayRoutineRouteImport } from './routes/_authenticated/play.routine'
import { Route as AuthenticatedPlaySequenceRouteImport } from './routes/_authenticated/play.sequence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaregiverRoute = AuthenticatedCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayFamilyRoute = AuthenticatedPlayFamilyRouteImport.update({
  id: '/play/family',
  path: '/play/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayPairsRoute = AuthenticatedPlayPairsRouteImport.update({
  id: '/play/pairs',
  path: '/play/pairs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoutineRoute =
  AuthenticatedPlayRoutineRouteImport.update({
    id: '/play/routine',
    path: '/play/routine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaySequenceRoute =
  AuthenticatedPlaySequenceRouteImport.update({
    id: '/play/sequence',
    path: '/play/sequence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caregiver': typeof AuthenticatedCaregiverRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/play/family': typeof AuthenticatedPlayFamilyRoute
  '/play/pairs': typeof AuthenticatedPlayPairsRoute
  '/play/routine': typeof AuthenticatedPlayRoutineRoute
  '/play/sequence': typeof AuthenticatedPlaySequenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caregiver': typeof AuthenticatedCaregiverRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/play/family': typeof AuthenticatedPlayFamilyRoute
  '/play/pairs': typeof AuthenticatedPlayPairsRoute
  '/play/routine': typeof AuthenticatedPlayRoutineRoute
  '/play/sequence': typeof AuthenticatedPlaySequenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/caregiver': typeof AuthenticatedCaregiverRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/play/family': typeof AuthenticatedPlayFamilyRoute
  '/_authenticated/play/pairs': typeof AuthenticatedPlayPairsRoute
  '/_authenticated/play/routine': typeof AuthenticatedPlayRoutineRoute
  '/_authenticated/play/sequence': typeof AuthenticatedPlaySequenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caregiver'
    | '/home'
    | '/profile'
    | '/play/family'
    | '/play/pairs'
    | '/play/routine'
    | '/play/sequence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caregiver'
    | '/home'
    | '/profile'
    | '/play/family'
    | '/play/pairs'
    | '/play/routine'
    | '/play/sequence'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/caregiver'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/play/family'
    | '/_authenticated/play/pairs'
    | '/_authenticated/play/routine'
    | '/_authenticated/play/sequence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/caregiver': {
      id: '/_authenticated/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof AuthenticatedCaregiverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/family': {
      id: '/_authenticated/play/family'
      path: '/play/family'
      fullPath: '/play/family'
      preLoaderRoute: typeof AuthenticatedPlayFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/pairs': {
      id: '/_authenticated/play/pairs'
      path: '/play/pairs'
      fullPath: '/play/pairs'
      preLoaderRoute: typeof AuthenticatedPlayPairsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/routine': {
      id: '/_authenticated/play/routine'
      path: '/play/routine'
      fullPath: '/play/routine'
      preLoaderRoute: typeof AuthenticatedPlayRoutineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/sequence': {
      id: '/_authenticated/play/sequence'
      path: '/play/sequence'
      fullPath: '/play/sequence'
      preLoaderRoute: typeof AuthenticatedPlaySequenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaregiverRoute: typeof AuthenticatedCaregiverRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPlayFamilyRoute: typeof AuthenticatedPlayFamilyRoute
  AuthenticatedPlayPairsRoute: typeof AuthenticatedPlayPairsRoute
  AuthenticatedPlayRoutineRoute: typeof AuthenticatedPlayRoutineRoute
  AuthenticatedPlaySequenceRoute: typeof AuthenticatedPlaySequenceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaregiverRoute: AuthenticatedCaregiverRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPlayFamilyRoute: AuthenticatedPlayFamilyRoute,
  AuthenticatedPlayPairsRoute: AuthenticatedPlayPairsRoute,
  AuthenticatedPlayRoutineRoute: AuthenticatedPlayRoutineRoute,
  AuthenticatedPlaySequenceRoute: AuthenticatedPlaySequenceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
